// AUTO-GENERATED from 'Get salty calendar.xlsx' (merged cells expanded).
export const CALENDAR_DATA = {
 "rooms": [
  [
   "PARENTS ROOM",
   3,
   "Triple \u2014 1 double + 1 single bed. Shares shower & bathroom with Kids Room."
  ],
  [
   "KIDS ROOM",
   2,
   "Double or twin (beds join or split), balcony. Shares shower & bathroom with Parents Room."
  ],
  [
   "THE SUITE",
   2,
   "Double or twin (beds join or split), private bathroom & shower."
  ],
  [
   "THE TOWER",
   2,
   "Double or twin (beds join or split), balcony. Apartment 1. Shares shower with Tiny Dancer."
  ],
  [
   "TINY DANCER",
   2,
   "Double bed (1-2 people). Apartment 1. Shares shower with The Tower."
  ],
  [
   "SHACKERS BAY",
   2,
   "Double or twin (beds join or split), balcony. Apartment 2. Shares bathroom with Love Shack."
  ],
  [
   "LOVE SHACK",
   2,
   "Double or twin (beds join or split). Apartment 2. Shares bathroom with Shakers Bay."
  ],
  [
   "THE BOSS",
   2,
   "Double or twin (beds join or split). Apartment 3. Shares shower with Thunder."
  ],
  [
   "THUNDER",
   2,
   "Double bed (1-2 people), balcony. Apartment 3. Shares shower with The Boss."
  ],
  [
   "APPART",
   4,
   "Apartment \u2014 sleeps up to 4."
  ]
 ],
 "bookings": [
  {
   "room": "PARENTS ROOM",
   "name": "Viviene + 1",
   "checkIn": "2025-10-13",
   "checkOut": "2025-10-16",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Hannah + 2",
   "checkIn": "2025-10-17",
   "checkOut": "2025-10-21",
   "adults": 3,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Taryn + 1",
   "checkIn": "2025-10-30",
   "checkOut": "2025-11-04",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "BNB"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Benedict + 1",
   "checkIn": "2025-11-09",
   "checkOut": "2025-11-11",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "BNB"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Jalal + 1",
   "checkIn": "2025-11-11",
   "checkOut": "2025-11-20",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Evie",
   "checkIn": "2025-11-23",
   "checkOut": "2025-11-25",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Britta + Hannah + 1",
   "checkIn": "2025-11-25",
   "checkOut": "2025-12-06",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BB + Surf",
   "board": "BB + Surf"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Lila",
   "checkIn": "2025-12-06",
   "checkOut": "2025-12-12",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Fatma + Darren",
   "checkIn": "2025-12-12",
   "checkOut": "2025-12-25",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Sander",
   "checkIn": "2025-12-25",
   "checkOut": "2026-02-01",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "PARENTS ROOM",
   "name": "free room",
   "checkIn": "2026-03-08",
   "checkOut": "2026-03-09",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP NTS"
  },
  {
   "room": "PARENTS ROOM",
   "name": "booking:3 prs",
   "checkIn": "2026-03-26",
   "checkOut": "2026-03-27",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Surf and Dance",
   "checkIn": "2026-03-30",
   "checkOut": "2026-03-31",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "PARENTS ROOM",
   "name": "Camille",
   "checkIn": "2026-04-17",
   "checkOut": "2026-04-19",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "PARENTS ROOM",
   "name": "?",
   "checkIn": "2026-05-01",
   "checkOut": "2026-05-03",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB?"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Jawad +2",
   "checkIn": "2026-06-05",
   "checkOut": "2026-06-06",
   "adults": 3,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Tommaso + 2",
   "checkIn": "2026-06-07",
   "checkOut": "2026-06-14",
   "adults": 3,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Elodie Durant",
   "checkIn": "2026-07-15",
   "checkOut": "2026-07-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "PARENTS ROOM",
   "name": "Aisha + 2",
   "checkIn": "2026-08-02",
   "checkOut": "2026-08-08",
   "adults": 3,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "PARENTS ROOM",
   "name": "Marrianna",
   "checkIn": "2026-08-09",
   "checkOut": "2026-08-17",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Marianna",
   "checkIn": "2026-08-17",
   "checkOut": "2026-08-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "PARENTS ROOM",
   "name": "Yazid + 2",
   "checkIn": "2026-08-18",
   "checkOut": "2026-08-23",
   "adults": 3,
   "children": 0,
   "status": "checked_in",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "PARENTS ROOM",
   "name": "NTS",
   "checkIn": "2026-09-04",
   "checkOut": "2026-09-11",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": "Surf Package",
   "board": "Surf & creative flow"
  },
  {
   "room": "PARENTS ROOM",
   "name": "NTS",
   "checkIn": "2026-09-14",
   "checkOut": "2026-09-21",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": "Surf Package",
   "board": "Surf & travel"
  },
  {
   "room": "PARENTS ROOM",
   "name": "POCKET SHELLS",
   "checkIn": "2026-09-21",
   "checkOut": "2026-09-28",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "PARENTS ROOM",
   "name": "Wiktoria retreat",
   "checkIn": "2026-10-05",
   "checkOut": "2026-10-09",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "PARENTS ROOM",
   "name": "Pauli retreat",
   "checkIn": "2026-10-09",
   "checkOut": "2026-10-16",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "PARENTS ROOM",
   "name": "POCKET SHELLS",
   "checkIn": "2026-10-16",
   "checkOut": "2026-10-23",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "PARENTS ROOM",
   "name": "NTS",
   "checkIn": "2026-10-23",
   "checkOut": "2026-10-30",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "PARENTS ROOM",
   "name": "NTS",
   "checkIn": "2026-11-11",
   "checkOut": "2026-11-18",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "KIDS ROOM",
   "name": "Talia + 1",
   "checkIn": "2025-10-18",
   "checkOut": "2025-10-25",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "KIDS ROOM",
   "name": "Benjamin + 1",
   "checkIn": "2025-11-02",
   "checkOut": "2025-11-09",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "BNB"
  },
  {
   "room": "KIDS ROOM",
   "name": "Cata's friends",
   "checkIn": "2025-11-09",
   "checkOut": "2025-11-11",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "KIDS ROOM",
   "name": "Cata's friends",
   "checkIn": "2025-11-14",
   "checkOut": "2025-11-16",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "KIDS ROOM",
   "name": "Paula + Sus",
   "checkIn": "2025-11-17",
   "checkOut": "2025-12-13",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "KIDS ROOM",
   "name": "Bram",
   "checkIn": "2025-12-15",
   "checkOut": "2025-12-20",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "KIDS ROOM",
   "name": "Line + 1",
   "checkIn": "2026-01-08",
   "checkOut": "2026-02-08",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "BNB"
  },
  {
   "room": "KIDS ROOM",
   "name": "Natalia Rak, Natalia Grabek",
   "checkIn": "2026-03-08",
   "checkOut": "2026-03-15",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP NTS"
  },
  {
   "room": "KIDS ROOM",
   "name": "booking 2 prs",
   "checkIn": "2026-03-26",
   "checkOut": "2026-03-27",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "Bb"
  },
  {
   "room": "KIDS ROOM",
   "name": "14 people",
   "checkIn": "2026-03-30",
   "checkOut": "2026-03-31",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "KIDS ROOM",
   "name": "Elyazid",
   "checkIn": "2026-04-15",
   "checkOut": "2026-04-16",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "KIDS ROOM",
   "name": "Fatima + 1",
   "checkIn": "2026-04-18",
   "checkOut": "2026-04-19",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "KIDS ROOM",
   "name": "Vasileios",
   "checkIn": "2026-04-20",
   "checkOut": "2026-04-21",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "KIDS ROOM",
   "name": "Charlotte (separate bed)",
   "checkIn": "2026-04-24",
   "checkOut": "2026-04-26",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "KIDS ROOM",
   "name": "?",
   "checkIn": "2026-05-01",
   "checkOut": "2026-05-03",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB?"
  },
  {
   "room": "KIDS ROOM",
   "name": "Mohammed +1",
   "checkIn": "2026-05-03",
   "checkOut": "2026-05-08",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "KIDS ROOM",
   "name": "Erika",
   "checkIn": "2026-05-09",
   "checkOut": "2026-06-01",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "KIDS ROOM",
   "name": "Mouna",
   "checkIn": "2026-06-05",
   "checkOut": "2026-06-09",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "BB + Surf",
   "board": "BB + 1 surf"
  },
  {
   "room": "KIDS ROOM",
   "name": "Florina",
   "checkIn": "2026-07-11",
   "checkOut": "2026-07-15",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "KIDS ROOM",
   "name": "Elodie Durant",
   "checkIn": "2026-07-15",
   "checkOut": "2026-07-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "KIDS ROOM",
   "name": "Ewa",
   "checkIn": "2026-07-18",
   "checkOut": "2026-07-23",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "KIDS ROOM",
   "name": "Hichame + 1",
   "checkIn": "2026-07-25",
   "checkOut": "2026-07-26",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "KIDS ROOM",
   "name": "Andrei Bostan",
   "checkIn": "2026-08-10",
   "checkOut": "2026-08-19",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "Booking"
  },
  {
   "room": "KIDS ROOM",
   "name": "Yazid + 2",
   "checkIn": "2026-08-19",
   "checkOut": "2026-08-23",
   "adults": 2,
   "children": 0,
   "status": "checked_in",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "KIDS ROOM",
   "name": "NTS",
   "checkIn": "2026-09-04",
   "checkOut": "2026-09-11",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "KIDS ROOM",
   "name": "NTS",
   "checkIn": "2026-09-14",
   "checkOut": "2026-09-21",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "KIDS ROOM",
   "name": "POCKET SHELLS",
   "checkIn": "2026-09-21",
   "checkOut": "2026-09-28",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "KIDS ROOM",
   "name": "Wiktoria retreat",
   "checkIn": "2026-10-05",
   "checkOut": "2026-10-09",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "KIDS ROOM",
   "name": "Pauli retreat",
   "checkIn": "2026-10-09",
   "checkOut": "2026-10-16",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "KIDS ROOM",
   "name": "POCKET SHELLS",
   "checkIn": "2026-10-16",
   "checkOut": "2026-10-23",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "KIDS ROOM",
   "name": "NTS",
   "checkIn": "2026-10-23",
   "checkOut": "2026-10-30",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "KIDS ROOM",
   "name": "NTS",
   "checkIn": "2026-11-11",
   "checkOut": "2026-11-18",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE SUITE",
   "name": "Lila",
   "checkIn": "2025-12-05",
   "checkOut": "2025-12-06",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "THE SUITE",
   "name": "Marie",
   "checkIn": "2025-12-25",
   "checkOut": "2025-12-31",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "THE SUITE",
   "name": "Marie",
   "checkIn": "2026-01-02",
   "checkOut": "2026-01-04",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "THE SUITE",
   "name": "Stefanie + Svine",
   "checkIn": "2026-01-08",
   "checkOut": "2026-01-09",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Kilian",
   "checkIn": "2026-01-09",
   "checkOut": "2026-01-11",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Julia Leszczak, Julita So\u0142tys",
   "checkIn": "2026-03-08",
   "checkOut": "2026-03-15",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP NTS"
  },
  {
   "room": "THE SUITE",
   "name": "Issy + Amy",
   "checkIn": "2026-03-16",
   "checkOut": "2026-03-17",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Evi",
   "checkIn": "2026-03-22",
   "checkOut": "2026-03-28",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Natasa",
   "checkIn": "2026-04-10",
   "checkOut": "2026-04-14",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "THE SUITE",
   "name": "Camille",
   "checkIn": "2026-04-17",
   "checkOut": "2026-04-19",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "THE SUITE",
   "name": "Mo Solaiman",
   "checkIn": "2026-04-19",
   "checkOut": "2026-04-26",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Reda",
   "checkIn": "2026-04-28",
   "checkOut": "2026-05-02",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Andr\u00e9",
   "checkIn": "2026-05-02",
   "checkOut": "2026-05-05",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Suzanne",
   "checkIn": "2026-05-07",
   "checkOut": "2026-05-10",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Sheila",
   "checkIn": "2026-05-10",
   "checkOut": "2026-05-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Simon",
   "checkIn": "2026-05-18",
   "checkOut": "2026-05-25",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Soufiane's  friend",
   "checkIn": "2026-05-26",
   "checkOut": "2026-05-27",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "friend"
  },
  {
   "room": "THE SUITE",
   "name": "Anders +1",
   "checkIn": "2026-05-27",
   "checkOut": "2026-05-29",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Alexander +1",
   "checkIn": "2026-05-29",
   "checkOut": "2026-06-04",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Riccardo Moro +1",
   "checkIn": "2026-06-05",
   "checkOut": "2026-06-09",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Anja",
   "checkIn": "2026-06-11",
   "checkOut": "2026-06-16",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Oum friends",
   "checkIn": "2026-06-16",
   "checkOut": "2026-06-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Imene",
   "checkIn": "2026-06-25",
   "checkOut": "2026-06-27",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "booking"
  },
  {
   "room": "THE SUITE",
   "name": "Elodie Durant",
   "checkIn": "2026-07-15",
   "checkOut": "2026-07-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "THE SUITE",
   "name": "Florina",
   "checkIn": "2026-07-18",
   "checkOut": "2026-07-21",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "THE SUITE",
   "name": "Matylda + Kasia",
   "checkIn": "2026-07-24",
   "checkOut": "2026-07-31",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP"
  },
  {
   "room": "THE SUITE",
   "name": "Marie",
   "checkIn": "2026-08-04",
   "checkOut": "2026-08-10",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "Booking"
  },
  {
   "room": "THE SUITE",
   "name": "Omar Koutouby +1",
   "checkIn": "2026-08-10",
   "checkOut": "2026-08-17",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "Bnb"
  },
  {
   "room": "THE SUITE",
   "name": "Rachid's friend",
   "checkIn": "2026-08-17",
   "checkOut": "2026-08-20",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "Carmen",
   "checkIn": "2026-08-20",
   "checkOut": "2026-08-23",
   "adults": 1,
   "children": 0,
   "status": "checked_in",
   "package": null,
   "board": "booking"
  },
  {
   "room": "THE SUITE",
   "name": "Tutti client",
   "checkIn": "2026-08-27",
   "checkOut": "2026-08-29",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE SUITE",
   "name": "NTS",
   "checkIn": "2026-09-04",
   "checkOut": "2026-09-11",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE SUITE",
   "name": "NTS",
   "checkIn": "2026-09-14",
   "checkOut": "2026-09-21",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE SUITE",
   "name": "POCKET SHELLS",
   "checkIn": "2026-09-21",
   "checkOut": "2026-09-28",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE SUITE",
   "name": "Wiktoria retreat",
   "checkIn": "2026-10-05",
   "checkOut": "2026-10-09",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE SUITE",
   "name": "Pauli retreat",
   "checkIn": "2026-10-09",
   "checkOut": "2026-10-16",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE SUITE",
   "name": "POCKET SHELLS",
   "checkIn": "2026-10-16",
   "checkOut": "2026-10-23",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE SUITE",
   "name": "NTS",
   "checkIn": "2026-10-23",
   "checkOut": "2026-10-30",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE SUITE",
   "name": "NTS",
   "checkIn": "2026-11-11",
   "checkOut": "2026-11-18",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": "2.0"
  },
  {
   "room": "THE SUITE",
   "name": "Sarah +1 (twin bed)",
   "checkIn": "2026-12-27",
   "checkOut": "2027-01-01",
   "adults": 2,
   "children": 0,
   "status": "confirmed",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE TOWER",
   "name": "Julia",
   "checkIn": "2025-12-25",
   "checkOut": "2026-01-11",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE TOWER",
   "name": "Leila + 1",
   "checkIn": "2026-01-11",
   "checkOut": "2026-01-16",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE TOWER",
   "name": "Lou",
   "checkIn": "2026-01-17",
   "checkOut": "2026-02-01",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE TOWER",
   "name": "Veronika",
   "checkIn": "2026-02-10",
   "checkOut": "2026-02-17",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP / NTS"
  },
  {
   "room": "THE TOWER",
   "name": "Dominika",
   "checkIn": "2026-03-08",
   "checkOut": "2026-03-15",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP NTS"
  },
  {
   "room": "THE TOWER",
   "name": "Natalia Volunteer",
   "checkIn": "2026-03-15",
   "checkOut": "2026-03-26",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "THE TOWER",
   "name": "Tazuri clients",
   "checkIn": "2026-03-26",
   "checkOut": "2026-03-30",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE TOWER",
   "name": "Pauli / Zuza",
   "checkIn": "2026-04-07",
   "checkOut": "2026-04-16",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "Collab"
  },
  {
   "room": "THE TOWER",
   "name": "Mila",
   "checkIn": "2026-04-16",
   "checkOut": "2026-04-19",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE TOWER",
   "name": "Ausrine",
   "checkIn": "2026-04-19",
   "checkOut": "2026-04-27",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "Collab"
  },
  {
   "room": "THE TOWER",
   "name": "Fabregues",
   "checkIn": "2026-04-30",
   "checkOut": "2026-05-03",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE TOWER",
   "name": "Madeleine",
   "checkIn": "2026-05-03",
   "checkOut": "2026-05-04",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE TOWER",
   "name": "Amdshutter",
   "checkIn": "2026-05-04",
   "checkOut": "2026-05-08",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "Content Creator"
  },
  {
   "room": "THE TOWER",
   "name": "Saad",
   "checkIn": "2026-05-14",
   "checkOut": "2026-05-17",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE TOWER",
   "name": "Sheila",
   "checkIn": "2026-05-18",
   "checkOut": "2026-06-12",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE TOWER",
   "name": "Arthur",
   "checkIn": "2026-06-14",
   "checkOut": "2026-06-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "THE TOWER",
   "name": "Mo",
   "checkIn": "2026-07-01",
   "checkOut": "2026-07-15",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "THE TOWER",
   "name": "Elodie Durant",
   "checkIn": "2026-07-15",
   "checkOut": "2026-07-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "THE TOWER",
   "name": "Mo",
   "checkIn": "2026-07-18",
   "checkOut": "2026-08-01",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "THE TOWER",
   "name": "Soufiane",
   "checkIn": "2026-08-01",
   "checkOut": "2026-08-11",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "THE TOWER",
   "name": "Megan",
   "checkIn": "2026-08-11",
   "checkOut": "2026-08-19",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP"
  },
  {
   "room": "THE TOWER",
   "name": "Andrei Bostan",
   "checkIn": "2026-08-19",
   "checkOut": "2026-08-20",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "Booking"
  },
  {
   "room": "THE TOWER",
   "name": "Rachid's friend",
   "checkIn": "2026-08-20",
   "checkOut": "2026-08-23",
   "adults": 1,
   "children": 0,
   "status": "checked_in",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE TOWER",
   "name": "NTS",
   "checkIn": "2026-09-04",
   "checkOut": "2026-09-11",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE TOWER",
   "name": "NTS",
   "checkIn": "2026-09-14",
   "checkOut": "2026-09-21",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE TOWER",
   "name": "POCKET SHELLS",
   "checkIn": "2026-09-21",
   "checkOut": "2026-09-28",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE TOWER",
   "name": "Wiktoria retreat",
   "checkIn": "2026-10-05",
   "checkOut": "2026-10-09",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": "8.0"
  },
  {
   "room": "THE TOWER",
   "name": "Pauli retreat",
   "checkIn": "2026-10-09",
   "checkOut": "2026-10-16",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE TOWER",
   "name": "POCKET SHELLS",
   "checkIn": "2026-10-16",
   "checkOut": "2026-10-23",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": "6.0"
  },
  {
   "room": "THE TOWER",
   "name": "NTS",
   "checkIn": "2026-10-23",
   "checkOut": "2026-10-30",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE TOWER",
   "name": "NTS",
   "checkIn": "2026-11-11",
   "checkOut": "2026-11-18",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "TINY DANCER",
   "name": "Nick Roberts",
   "checkIn": "2025-12-09",
   "checkOut": "2025-12-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "TINY DANCER",
   "name": "Fatma + Darren",
   "checkIn": "2025-12-25",
   "checkOut": "2025-12-28",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "TINY DANCER",
   "name": "Davidi",
   "checkIn": "2025-12-28",
   "checkOut": "2025-12-31",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "TINY DANCER",
   "name": "Davidi + Maddalina",
   "checkIn": "2025-12-31",
   "checkOut": "2026-01-04",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "TINY DANCER",
   "name": "Marie",
   "checkIn": "2026-01-04",
   "checkOut": "2026-01-22",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "TINY DANCER",
   "name": "Philip",
   "checkIn": "2026-01-31",
   "checkOut": "2026-02-10",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "TINY DANCER",
   "name": "Klaudia",
   "checkIn": "2026-03-07",
   "checkOut": "2026-03-15",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP NTS"
  },
  {
   "room": "TINY DANCER",
   "name": "Tazuri clients",
   "checkIn": "2026-03-26",
   "checkOut": "2026-03-30",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "TINY DANCER",
   "name": "Verena",
   "checkIn": "2026-04-05",
   "checkOut": "2026-07-01",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "Social host"
  },
  {
   "room": "TINY DANCER",
   "name": "Elodie Durant",
   "checkIn": "2026-07-15",
   "checkOut": "2026-07-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "TINY DANCER",
   "name": "Nina",
   "checkIn": "2026-07-18",
   "checkOut": "2026-08-19",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "Social host"
  },
  {
   "room": "TINY DANCER",
   "name": "POCKET SHELLS",
   "checkIn": "2026-09-21",
   "checkOut": "2026-09-28",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "TINY DANCER",
   "name": "Wiktoria retreat",
   "checkIn": "2026-10-05",
   "checkOut": "2026-10-09",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "TINY DANCER",
   "name": "Pauli retreat",
   "checkIn": "2026-10-09",
   "checkOut": "2026-10-16",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "TINY DANCER",
   "name": "POCKET SHELLS",
   "checkIn": "2026-10-16",
   "checkOut": "2026-10-23",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "TINY DANCER",
   "name": "NTS",
   "checkIn": "2026-10-23",
   "checkOut": "2026-10-30",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "TINY DANCER",
   "name": "NTS",
   "checkIn": "2026-11-11",
   "checkOut": "2026-11-18",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "SHACKERS BAY",
   "name": "Johannes",
   "checkIn": "2025-12-25",
   "checkOut": "2026-01-17",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Rafa",
   "checkIn": "2026-01-18",
   "checkOut": "2026-01-21",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Tadeusz, Karol",
   "checkIn": "2026-03-08",
   "checkOut": "2026-03-15",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP NTS"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Julita",
   "checkIn": "2026-03-27",
   "checkOut": "2026-03-30",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "Host"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Wicktoria",
   "checkIn": "2026-04-11",
   "checkOut": "2026-04-17",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "Collab"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Hatim + 1",
   "checkIn": "2026-04-17",
   "checkOut": "2026-04-19",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Charline Delux apt booking",
   "checkIn": "2026-04-21",
   "checkOut": "2026-04-26",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Lais +1",
   "checkIn": "2026-05-01",
   "checkOut": "2026-05-04",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Ismail",
   "checkIn": "2026-05-07",
   "checkOut": "2026-05-10",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Ousama",
   "checkIn": "2026-05-16",
   "checkOut": "2026-05-25",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Soufiane's friend",
   "checkIn": "2026-05-27",
   "checkOut": "2026-05-29",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "friend"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Alexandra (2adults + 2 kids)",
   "checkIn": "2026-06-04",
   "checkOut": "2026-06-11",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Karim Bellahcene",
   "checkIn": "2026-06-15",
   "checkOut": "2026-06-17",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Hassan Ouhadou",
   "checkIn": "2026-07-05",
   "checkOut": "2026-07-08",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Zineb",
   "checkIn": "2026-07-08",
   "checkOut": "2026-07-15",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Elodie Durant",
   "checkIn": "2026-07-15",
   "checkOut": "2026-07-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "SHACKERS BAY",
   "name": "Oualid",
   "checkIn": "2026-07-18",
   "checkOut": "2026-07-22",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Assia +3",
   "checkIn": "2026-07-23",
   "checkOut": "2026-07-26",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "BNB"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Saad + 3",
   "checkIn": "2026-07-26",
   "checkOut": "2026-07-29",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "BNB"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Boutaina + 2",
   "checkIn": "2026-07-31",
   "checkOut": "2026-08-04",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "Bnb"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Othmane",
   "checkIn": "2026-08-04",
   "checkOut": "2026-08-06",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "BNB"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Sara + 1",
   "checkIn": "2026-08-08",
   "checkOut": "2026-08-13",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "Bnb"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Taoubi + 2",
   "checkIn": "2026-08-13",
   "checkOut": "2026-08-16",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "Bnb"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Alae + 2",
   "checkIn": "2026-08-16",
   "checkOut": "2026-08-19",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Benjamin + 2",
   "checkIn": "2026-08-20",
   "checkOut": "2026-08-24",
   "adults": 2,
   "children": 0,
   "status": "checked_in",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Oussama",
   "checkIn": "2026-08-24",
   "checkOut": "2026-08-27",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": "BNB",
   "board": "Bnb"
  },
  {
   "room": "SHACKERS BAY",
   "name": "Oualid",
   "checkIn": "2026-08-28",
   "checkOut": "2026-08-31",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "SHACKERS BAY",
   "name": "POCKET SHELLS",
   "checkIn": "2026-09-21",
   "checkOut": "2026-09-28",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "SHACKERS BAY",
   "name": "Wiktoria retreat",
   "checkIn": "2026-10-05",
   "checkOut": "2026-10-09",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "SHACKERS BAY",
   "name": "Pauli retreat",
   "checkIn": "2026-10-09",
   "checkOut": "2026-10-16",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "SHACKERS BAY",
   "name": "POCKET SHELLS",
   "checkIn": "2026-10-16",
   "checkOut": "2026-10-23",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "SHACKERS BAY",
   "name": "NTS",
   "checkIn": "2026-10-23",
   "checkOut": "2026-10-30",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "SHACKERS BAY",
   "name": "NTS",
   "checkIn": "2026-11-11",
   "checkOut": "2026-11-18",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "LOVE SHACK",
   "name": "Fatma + Darren",
   "checkIn": "2025-12-28",
   "checkOut": "2026-01-10",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "LOVE SHACK",
   "name": "Rafa\u0142",
   "checkIn": "2026-03-07",
   "checkOut": "2026-03-08",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP NTS"
  },
  {
   "room": "LOVE SHACK",
   "name": "Rafa\u0142, Artur",
   "checkIn": "2026-03-08",
   "checkOut": "2026-03-15",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP NTS"
  },
  {
   "room": "LOVE SHACK",
   "name": "Tazuri clients",
   "checkIn": "2026-03-26",
   "checkOut": "2026-03-30",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "LOVE SHACK",
   "name": "Kalle",
   "checkIn": "2026-04-12",
   "checkOut": "2026-04-17",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "LOVE SHACK",
   "name": "Hatim + 1",
   "checkIn": "2026-04-17",
   "checkOut": "2026-04-19",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "LOVE SHACK",
   "name": "Charline Delux apt booking",
   "checkIn": "2026-04-21",
   "checkOut": "2026-04-26",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "LOVE SHACK",
   "name": "Lais +1",
   "checkIn": "2026-05-01",
   "checkOut": "2026-05-04",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "LOVE SHACK",
   "name": "SAW",
   "checkIn": "2026-05-06",
   "checkOut": "2026-05-09",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "LOVE SHACK",
   "name": "Nouaman",
   "checkIn": "2026-05-24",
   "checkOut": "2026-05-29",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "Friend"
  },
  {
   "room": "LOVE SHACK",
   "name": "Alexandra (2adults + 2 kids)",
   "checkIn": "2026-06-04",
   "checkOut": "2026-06-11",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "LOVE SHACK",
   "name": "Yassir",
   "checkIn": "2026-06-15",
   "checkOut": "2026-06-19",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "LOVE SHACK",
   "name": "Hassan Ouhadou",
   "checkIn": "2026-07-05",
   "checkOut": "2026-07-08",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "LOVE SHACK",
   "name": "Zineb",
   "checkIn": "2026-07-08",
   "checkOut": "2026-07-15",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "LOVE SHACK",
   "name": "Elodie Durant",
   "checkIn": "2026-07-15",
   "checkOut": "2026-07-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "LOVE SHACK",
   "name": "Oualid",
   "checkIn": "2026-07-18",
   "checkOut": "2026-07-22",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "LOVE SHACK",
   "name": "Assia +3",
   "checkIn": "2026-07-23",
   "checkOut": "2026-07-26",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "BNB"
  },
  {
   "room": "LOVE SHACK",
   "name": "Saad + 3",
   "checkIn": "2026-07-26",
   "checkOut": "2026-07-29",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "BNB"
  },
  {
   "room": "LOVE SHACK",
   "name": "Boutaina + 2",
   "checkIn": "2026-07-31",
   "checkOut": "2026-08-04",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "Bnb"
  },
  {
   "room": "LOVE SHACK",
   "name": "Othmane",
   "checkIn": "2026-08-04",
   "checkOut": "2026-08-06",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "BNB"
  },
  {
   "room": "LOVE SHACK",
   "name": "Sara + 1",
   "checkIn": "2026-08-08",
   "checkOut": "2026-08-13",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "Bnb"
  },
  {
   "room": "LOVE SHACK",
   "name": "Taoubi + 2",
   "checkIn": "2026-08-13",
   "checkOut": "2026-08-16",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "BNB",
   "board": "Bnb"
  },
  {
   "room": "LOVE SHACK",
   "name": "Alae + 2",
   "checkIn": "2026-08-16",
   "checkOut": "2026-08-19",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "LOVE SHACK",
   "name": "Benjamin + 2",
   "checkIn": "2026-08-20",
   "checkOut": "2026-08-24",
   "adults": 2,
   "children": 0,
   "status": "checked_in",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "LOVE SHACK",
   "name": "Oussama",
   "checkIn": "2026-08-24",
   "checkOut": "2026-08-27",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": "BNB",
   "board": "Bnb"
  },
  {
   "room": "LOVE SHACK",
   "name": "Oualid",
   "checkIn": "2026-08-28",
   "checkOut": "2026-08-31",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "LOVE SHACK",
   "name": "POCKET SHELLS",
   "checkIn": "2026-09-21",
   "checkOut": "2026-09-28",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "LOVE SHACK",
   "name": "Wiktoria retreat",
   "checkIn": "2026-10-05",
   "checkOut": "2026-10-09",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "LOVE SHACK",
   "name": "Pauli retreat",
   "checkIn": "2026-10-09",
   "checkOut": "2026-10-16",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "LOVE SHACK",
   "name": "POCKET SHELLS",
   "checkIn": "2026-10-16",
   "checkOut": "2026-10-23",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "LOVE SHACK",
   "name": "NTS",
   "checkIn": "2026-10-23",
   "checkOut": "2026-10-30",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "LOVE SHACK",
   "name": "NTS",
   "checkIn": "2026-11-11",
   "checkOut": "2026-11-18",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE BOSS",
   "name": "Kilian",
   "checkIn": "2025-12-27",
   "checkOut": "2026-01-08",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE BOSS",
   "name": "Paulina Pilates",
   "checkIn": "2026-03-07",
   "checkOut": "2026-03-17",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP NTS"
  },
  {
   "room": "THE BOSS",
   "name": "Paulina",
   "checkIn": "2026-03-23",
   "checkOut": "2026-03-30",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE BOSS",
   "name": "Lindsay",
   "checkIn": "2026-04-12",
   "checkOut": "2026-04-13",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE BOSS",
   "name": "Pia + Mia",
   "checkIn": "2026-04-13",
   "checkOut": "2026-04-15",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE BOSS",
   "name": "Mila",
   "checkIn": "2026-04-15",
   "checkOut": "2026-04-16",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE BOSS",
   "name": "Issy",
   "checkIn": "2026-04-18",
   "checkOut": "2026-04-27",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "Collab"
  },
  {
   "room": "THE BOSS",
   "name": "Essi",
   "checkIn": "2026-05-01",
   "checkOut": "2026-05-03",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE BOSS",
   "name": "MO",
   "checkIn": "2026-05-03",
   "checkOut": "2026-05-09",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE BOSS",
   "name": "Yousef",
   "checkIn": "2026-05-16",
   "checkOut": "2026-06-01",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "Offer"
  },
  {
   "room": "THE BOSS",
   "name": "Manon",
   "checkIn": "2026-06-07",
   "checkOut": "2026-06-10",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THE BOSS",
   "name": "Elodie Durant",
   "checkIn": "2026-07-15",
   "checkOut": "2026-07-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "THE BOSS",
   "name": "Mouhsine",
   "checkIn": "2026-08-02",
   "checkOut": "2026-08-23",
   "adults": 1,
   "children": 0,
   "status": "checked_in",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "THE BOSS",
   "name": "Mia Wagner +1",
   "checkIn": "2026-09-23",
   "checkOut": "2026-09-26",
   "adults": 2,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": "Package"
  },
  {
   "room": "THE BOSS",
   "name": "Wiktoria retreat",
   "checkIn": "2026-10-05",
   "checkOut": "2026-10-09",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE BOSS",
   "name": "Megan W",
   "checkIn": "2026-10-23",
   "checkOut": "2026-10-30",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THE BOSS",
   "name": "NTS",
   "checkIn": "2026-11-11",
   "checkOut": "2026-11-18",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THUNDER",
   "name": "Stefanie",
   "checkIn": "2025-12-27",
   "checkOut": "2026-01-03",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THUNDER",
   "name": "Stefanie + Svine",
   "checkIn": "2026-01-03",
   "checkOut": "2026-01-08",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "THUNDER",
   "name": "Soufiane",
   "checkIn": "2026-03-07",
   "checkOut": "2026-03-17",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "THUNDER",
   "name": "Soufiane",
   "checkIn": "2026-04-11",
   "checkOut": "2026-05-01",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "THUNDER",
   "name": "Mohammed +1",
   "checkIn": "2026-05-01",
   "checkOut": "2026-05-02",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "THUNDER",
   "name": "Soufiane",
   "checkIn": "2026-05-02",
   "checkOut": "2026-07-15",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "THUNDER",
   "name": "Elodie Durant",
   "checkIn": "2026-07-15",
   "checkOut": "2026-07-18",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "THUNDER",
   "name": "Soufiane",
   "checkIn": "2026-07-18",
   "checkOut": "2026-08-01",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "THUNDER",
   "name": "Mouhsine",
   "checkIn": "2026-08-02",
   "checkOut": "2026-08-23",
   "adults": 1,
   "children": 0,
   "status": "checked_in",
   "package": "Room Only",
   "board": "RO"
  },
  {
   "room": "THUNDER",
   "name": "NTS",
   "checkIn": "2026-09-04",
   "checkOut": "2026-09-11",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THUNDER",
   "name": "Jessy",
   "checkIn": "2026-09-21",
   "checkOut": "2026-09-28",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": "Package"
  },
  {
   "room": "THUNDER",
   "name": "Wiktoria retreat",
   "checkIn": "2026-10-05",
   "checkOut": "2026-10-09",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "THUNDER",
   "name": "NTS",
   "checkIn": "2026-11-11",
   "checkOut": "2026-11-18",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "APPART",
   "name": "Pauline +1",
   "checkIn": "2026-06-04",
   "checkOut": "2026-06-05",
   "adults": 2,
   "children": 0,
   "status": "checked_out",
   "package": "Bed & Breakfast",
   "board": "BB"
  },
  {
   "room": "APPART",
   "name": "Rent",
   "checkIn": "2026-06-08",
   "checkOut": "2026-06-11",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "APPART",
   "name": "Hassan",
   "checkIn": "2026-07-08",
   "checkOut": "2026-07-11",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "APPART",
   "name": "Bjork",
   "checkIn": "2026-07-12",
   "checkOut": "2026-07-21",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": "SP"
  },
  {
   "room": "APPART",
   "name": "Lars",
   "checkIn": "2026-08-08",
   "checkOut": "2026-08-13",
   "adults": 1,
   "children": 0,
   "status": "checked_out",
   "package": null,
   "board": null
  },
  {
   "room": "APPART",
   "name": "Soufiane",
   "checkIn": "2026-08-13",
   "checkOut": "2026-09-01",
   "adults": 1,
   "children": 0,
   "status": "checked_in",
   "package": null,
   "board": null
  },
  {
   "room": "APPART",
   "name": "Goal",
   "checkIn": "2026-09-01",
   "checkOut": "2026-09-02",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": "30 pax"
  },
  {
   "room": "APPART",
   "name": "3.0",
   "checkIn": "2026-09-04",
   "checkOut": "2026-09-05",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "APPART",
   "name": "7.0",
   "checkIn": "2026-09-14",
   "checkOut": "2026-09-15",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "APPART",
   "name": "8.0",
   "checkIn": "2026-09-21",
   "checkOut": "2026-09-22",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": null
  },
  {
   "room": "APPART",
   "name": "Goal",
   "checkIn": "2026-10-02",
   "checkOut": "2026-10-03",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": "40 pax"
  },
  {
   "room": "APPART",
   "name": "Goal",
   "checkIn": "2026-11-01",
   "checkOut": "2026-11-02",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": "40 pax"
  },
  {
   "room": "APPART",
   "name": "Goal",
   "checkIn": "2026-12-02",
   "checkOut": "2026-12-03",
   "adults": 1,
   "children": 0,
   "status": "confirmed",
   "package": null,
   "board": "50 pax"
  }
 ],
 "blocks": [
  {
   "room": "PARENTS ROOM",
   "start": "2026-02-10",
   "end": "2026-02-17",
   "reason": "Blocked"
  },
  {
   "room": "KIDS ROOM",
   "start": "2025-12-28",
   "end": "2026-01-08",
   "reason": "Blocked"
  },
  {
   "room": "KIDS ROOM",
   "start": "2026-02-10",
   "end": "2026-02-17",
   "reason": "Blocked"
  },
  {
   "room": "THE SUITE",
   "start": "2025-10-01",
   "end": "2025-12-04",
   "reason": "Under renovation"
  },
  {
   "room": "THE TOWER",
   "start": "2025-10-01",
   "end": "2025-12-04",
   "reason": "Under renovation"
  },
  {
   "room": "TINY DANCER",
   "start": "2025-10-01",
   "end": "2025-12-04",
   "reason": "Under renovation"
  },
  {
   "room": "SHACKERS BAY",
   "start": "2025-11-02",
   "end": "2025-11-09",
   "reason": "Blocked"
  },
  {
   "room": "SHACKERS BAY",
   "start": "2025-11-17",
   "end": "2025-12-10",
   "reason": "Blocked"
  },
  {
   "room": "LOVE SHACK",
   "start": "2025-11-02",
   "end": "2025-11-09",
   "reason": "Blocked"
  },
  {
   "room": "LOVE SHACK",
   "start": "2025-11-17",
   "end": "2025-12-10",
   "reason": "Blocked"
  },
  {
   "room": "THE BOSS",
   "start": "2025-10-30",
   "end": "2025-11-04",
   "reason": "Blocked"
  },
  {
   "room": "THE BOSS",
   "start": "2025-11-09",
   "end": "2025-11-11",
   "reason": "Blocked"
  },
  {
   "room": "THE BOSS",
   "start": "2025-11-25",
   "end": "2025-12-06",
   "reason": "Blocked"
  },
  {
   "room": "THE BOSS",
   "start": "2026-01-08",
   "end": "2026-02-08",
   "reason": "Blocked"
  },
  {
   "room": "THUNDER",
   "start": "2025-10-30",
   "end": "2025-11-04",
   "reason": "Blocked"
  },
  {
   "room": "THUNDER",
   "start": "2025-11-09",
   "end": "2025-11-11",
   "reason": "Blocked"
  },
  {
   "room": "THUNDER",
   "start": "2025-11-25",
   "end": "2025-12-06",
   "reason": "Blocked"
  },
  {
   "room": "THUNDER",
   "start": "2026-01-08",
   "end": "2026-02-08",
   "reason": "Blocked"
  }
 ]
} as const;
